server:
  port: 8199
spring:
 application:
   name: PCF Spring PostrgeSQL Demo
 datasource:
   url: jdbc:postgresql://localhost:5432/elections
   username: postgres
   password: postgres1234
   driver-class-name: org.postgresql.Driver
 jpa:
   show-sql: true
message: The 'default' Profile Active
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
 level:
   root: INFO
---
spring:
 profiles: dev
message: The 'dev' Environment Profile Active
logging:
 level:
   root: DEBUG
---
spring:
 profiles: test
message: The 'test' Environment Profile Active
logging:
 level:
   root: DEBUG
---
spring:
 profiles: prod
 datasource:
   url: <use_environment_variable>
   username: <use_environment_variable>
   password: <use_environment_variable>
 jpa:
   show-sql: true
message: The 'prod' Environment Profile Active
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info"]
logging:
 level:
   root: WARN