apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: uat-ingress
  labels:
    name: uat-ingress
  namespace: uat
  annotations:
    kubernetes.io/ingress.class: istio
spec:
  rules:
  - http:
      paths:
      - path: /uat/.*
        backend:
          serviceName: election
          servicePort: 8080
    host: api.uat.voter-demo.com
